version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mon-app
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network
    volumes:
      - static-data:/usr/share/nginx/html:ro

networks:
  app-network:

volumes:
  static-data: