name: Build & Deploy


on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


env:
# tout garder en minuscule pour GHCR ( Git Hub Container Registry)
  IMAGE_NAME: ghcr.io/krisdevo/signmailmaker:latest


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u krisdevo --password-stdin


      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .


      - name: Push Docker image
        run: docker push $IMAGE_NAME


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
     - name: Deploy over SSH (root)
       uses: appleboy/ssh-action@v1.2.0
       with:
        host: ${{ secrets.SSH_HOST }} # ipv4 du server ovh vps
        username: ${{ secrets.SSH_USER }} # root
        key: ${{ secrets.SSH_KEY }}       # clé privée OPENSSH (begin/end) ( dans le pc user/)
        script: |
          set -euo pipefail
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u asyylia --password-stdin
          docker rm -f signmail_web 2>/dev/null || true
          docker compose -f /opt/signmail/docker-compose.prod.yml pull
          docker compose -f /opt/signmail/docker-compose.prod.yml up -d --remove-orphans --force-recreate
          docker ps


